# Generated by Django 3.2 on 2022-06-17 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout', models.DateTimeField()),
                ('previous_reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_rental', to='booking.rental')),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='booking.rental')),
            ],
        ),
    ]
