# Generated by Django 3.2 on 2022-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_reservation',
            field=models.IntegerField(null=True),
        ),
    ]
